# Generated by Django 4.2.18 on 2025-12-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_project_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
