# Generated by Django 4.2.18 on 2025-12-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_review_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_created',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('Up', 'Up_vote'), ('Down', 'Down_vote')], max_length=200),
        ),
    ]
